---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: 介紹使用 Amazon EVS 和 Amazon FSx for NetApp ONTAP 進行 BlueXP 災難復原。 
---
= 使用 Amazon Elastic VMware Service 和 Amazon FSx for NetApp ONTAP 介紹 BlueXP 災難復原
:allow-uri-read: 


[role="lead"]
客戶越來越依賴虛擬化基礎架構來處理生產運算工作負載，例如基於 VMware vSphere 的基礎架構。隨著這些虛擬機器 (VM) 對業務的重要性日益提升，客戶需要保護這些虛擬機器免受與實體運算資源相同類型的災難的影響。目前提供的災難復原 (DR) 解決方案既複雜又昂貴，而且資源密集。作為最大的虛擬化基礎架構儲存供應商，NetApp 致力於確保其客戶的虛擬機器受到與我們保護 ONTAP 儲存託管的任何類型的資料相同的保護。為了實現這一目標，NetApp 創建了 BlueXP 災難復原服務​​。


NOTE: 有關 AMAZON EVS 的本文檔作為技術預覽提供。透過此預覽方案、 NetApp 保留在「一般供應」之前修改產品詳細資料、內容和時間表的權利。

任何災難復原解決方案面臨的主要挑戰之一是，僅僅為了提供災難復原複製和復原基礎架構，就需要管理購買、配置和維護額外運算、網路和儲存資源的增量成本。保護關鍵本地虛擬資源的常見選擇是使用雲端託管虛擬資源作為災難復原複製和復原基礎架構。亞馬遜就是此類解決方案的一個例子，它可以提供與 NetApp ONTAP 託管虛擬機器基礎架構相容的經濟高效的資源。

亞馬遜推出了 Amazon Elastic VMware 服務 (Amazon EVS)，該服務可在您的虛擬私有雲 (VPC) 中支援 VMware Cloud Foundation。 AmazonEVS 提供 AWS 的彈性和效能，以及熟悉的 VMware 軟體和工具，使 Amazon EVS vCenters 可以整合到您的本地虛擬化基礎架構中作為擴充。

雖然 Amazon EVS 附帶儲存資源，但對於儲存工作負載繁重的組織來說，使用原生儲存可能會降低其效率。在這種情況下，將 Amazon EVS 與 Amazon FSx for NetApp ONTAP 儲存 (Amazon FSxN) 結合使用可以提供更靈活的儲存解決方案。此外，當您在本機上使用 NetApp ONTAP 儲存解決方案託管 VMware 基礎架構時，將 Amazon EVS 與 FSx for ONTAP 結合使用表示您可以在本機和雲端託管基礎架構之間取得一流的資料互通性和保護功能。

如需 Amazon FSX for NetApp ONTAP 的相關資訊、請參閱 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Amazon FSX for NetApp ONTAP 功能入門"^]。
