---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-enable-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: 介紹使用 Amazon EVS 和 Amazon FSx for NetApp ONTAP 進行 BlueXP 災難復原。 BlueXP災難復原是一款授權產品，必須先購買才能使用。我們提供多種類型的許可證，並且有多種購買方式。 
---
= 將 BlueXP 災難復原服務​​新增至您的 Amazon EVS 的 BlueXP 帳戶
:allow-uri-read: 


[role="lead"]
BlueXP 災難復原是一款授權產品，必須先購買才能使用。我們提供多種類型的許可證，您可以透過多種方式購買許可證。許可證可讓您在特定時間段內保護特定數量的資料。

有關 BlueXP 災難復原許可證的更多信息，請參閱link:../get-started/dr-licensing.html["設定 BlueXP 災難恢復的授權"] 。



== 授權類型

主要有兩種許可證類型：

* NetApp 提供link:../get-started/dr-licensing.html["30天試用許可證"]您可以使用它來評估使用 ONTAP 和 VMware 資源的 BlueXP 災難復原。此許可證提供 30 天的使用期限，可無限量使用受保護的容量。
* 如果您希望在 30 天試用期結束後獲得災難復原保護，請購買生產許可證。您可以透過任何 NetApp 雲端合作夥伴的市場購買此許可證，但在本指南中，我們建議您使用 Amazon AWS Marketplace 購買用於 BlueXP 災難復原的 *NetApp 智慧服務* 授權。要了解有關透過 Amazon Marketplace 購買許可證的更多信息，請參閱link:../get-started/dr-licensing.html["透過 AWS Marketplace 訂閱"] 。




== 確定災難復原容量需求

在購買許可證之前，您應該了解需要保護多少 ONTAP 儲存容量。使用 NetApp ONTAP 儲存的優點之一是 NetApp 儲存資料的高效率。所有儲存在 ONTAP 磁碟區中的資料（例如託管虛擬機器的 VMware 資料儲存區）都以高效的方式儲存。將資料寫入實體儲存時，ONTAP 預設採用三種儲存效率：壓縮、重複資料刪除和資料壓縮。最終結果是儲存效率在 1.5:1 到 4:1 之間，具體取決於儲存的資料類型。事實上，NetApp 提供了 https://www.netapp.com/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf["儲存效率保證"^]對於某些工作負載。

這會對您有利，因為 BlueXP 災難復原會在應用所有 ONTAP 儲存效率後計算許可容量。例如，假設您在 vCenter 中設定了一個 100 TB (TiB) 的 NFS 資料儲存區，用於託管 100 台要使用該服務保護的虛擬機器。此外，假設當資料寫入 ONTAP 磁碟區時，自動應用的儲存效率技術會使這些虛擬機器僅消耗 33 TiB（3:1 的儲存效率）。那麼BlueXP 災難復原只需獲得 33 TiB 的許可，而不是 100 TiB。與其他災難復原解決方案相比，這將大大降低您的災難復原解決方案的總擁有成本。

.步驟
. 若要確定託管要保護的 VMware 資料儲存庫的每個磁碟區上消耗的資料量，請透過對每個磁碟區執行 ONTAP CLI 命令來確定磁碟容量消耗：  `volume show-space -volume < _volume name_ > -vserver < _SVM name_ >` 。
+
例如：

+
[listing]
----
cluster1::> volume show-space
Vserver : vm-nfs-ds1
Volume  : vol0
Feature                                Used      Used%
-----------------------------      --------     ------
User Data                           163.4MB         3%
Filesystem Metadata                   172KB         0%
Inodes                               2.93MB         0%
Snapshot Reserve                    292.9MB         5%
Total Metadata                        185KB         0%
Total Used                          459.4MB         8%
Total Physical Used                 166.4MB         3%

----
. 記下每個磁碟區的「總物理已用量」值。這是 BlueXP 災難復原需要保護的資料量，您將使用該值來確定需要許可的容量。

