---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, 
summary: 若要使用 BlueXP 災難恢復、請執行幾個步驟來設定。 
---
= 設定 BlueXP 災難恢復
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
若要使用 BlueXP 災難恢復、請執行幾個步驟、在 AWS 和 BlueXP 中同時設定。


TIP: 檢閱 link:../get-started/dr-prerequisites.html["先決條件"] 確保您的環境已準備就緒。



== 在 AWS 中設定

在 AWS 中、您需要執行下列步驟：

* 在 AWS 上部署和設定 VMware Cloud 。
* 為 ONTAP 檔案系統建立 Amazon FSX 。為 ONTAP 配置和設定 FSX 。
* 使用 VMware 帳戶並配置軟體定義資料中心（ SDDC ）。確保 SDDC 與適用於 ONTAP 的 FSX 有連線。




=== 部署 VMware Cloud

https://www.vmware.com/products/vmc-on-aws.html["AWS上的VMware Cloud"^] 為AWS生態系統中的VMware工作負載提供雲端原生體驗。每個 VMware 軟體定義資料中心（ SDDC ）都會在 Amazon Virtual Private Cloud （ VPC ）中執行、並提供完整的 VMware 堆疊（包括 vCenter Server ）、 NSX-T 軟體定義網路、 vSAN 軟體定義儲存設備、以及一或多個 ESXi 主機、為工作負載提供運算和儲存資源。

若要在AWS上設定VMC環境、請執行下列步驟 https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["連結"^]。試行指示燈叢集也可用於災難恢復。



=== 設定 Amazon FSX for NetApp ONTAP

Amazon FSX for NetApp ONTAP Sfing是一項全託管服務、以熱門的NetApp ONTAP Sfor NetApp文件系統為基礎、提供高度可靠、可擴充、高效能且功能豐富的檔案儲存設備。請依照下列步驟操作 https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["連結"^] 為 NetApp ONTAP 配置和設定 FSX 。



== 在 BlueXP 中設定

下一步是在 BlueXP 中設定災難恢復。

* 在 BlueXP 中建立 Connector 。
* 部署及設定 SnapMirror for Amazon FSX for NetApp ONTAP 。
* 將內部部署 ONTAP 儲存工作環境新增至 BlueXP 。這是來源 ONTAP 叢集。
* 新增 BlueXP 帳戶、將 FSxN 新增至工作環境、並新增適用於 ONTAP 的 FSx 的 AWS 認證。




=== 在 BlueXP 中建立 Connector

您必須註冊預覽、或聯絡 NetApp 銷售代表、才能試用這項服務。然後、當您使用 BlueXP Connector 時、它會包含災難恢復服務的適當功能。

若要在使用此服務之前在 BlueXP 中建立 Connector 、請參閱說明的 BlueXP 文件 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["如何建立連接器"^]。

使用 BlueXP 內部部署 Connector 或 BlueXP AWS Connector 、可存取來源內部部署 vCenter 和目的地內部部署 vCenter 。



=== 針對 Amazon FSX for NetApp ONTAP 設定 SnapMirror

下一步是在 BlueXP 中設定災難恢復。

. 在 BlueXP 中、新增帳戶。請參閱 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-netapp-accounts.html["BlueXP 說明文件、說明如何新增帳戶"^]。
. 將 Amazon FSX for NetApp ONTAP 新增至工作環境。確保與 ONTAP 叢集的 SnapMirror 關係已就緒、且其目的地為 NetApp ONTAP 的 FSX 。請參閱 https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["如何為 ONTAP 工作環境設定 FSX"^]。
. 在 BlueXP 中、將 SnapMirror 部署至適用於 NetApp ONTAP 的 FSX 。
. 在 BlueXP 中、探索 AWS 執行個體上的已配置 FSX for NetApp ONTAP 、並以適當的頻率和 NetApp Snapshot 複製保留、將指定的資料存放區磁碟區從內部環境複寫到適用於 NetApp ONTAP 的 FSX 。

