---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas, disaster 
summary: BlueXP 災難恢復是一種雲端型災難恢復服務、可自動化災難恢復工作流程。有了適用於 VMware 的 BlueXP 災難恢復功能、您可以使用 NetApp 雲端儲存設備、將執行 ONTAP 儲存設備的內部部署 VMware 工作負載複寫到公有雲中的 VMware 軟體定義資料中心、做為災難恢復站台。 
---
= BlueXP  災難恢復的新功能
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解 BlueXP 災難恢復的新功能。



== 2025年9月15日

版本 4.3.5P3



=== 測試故障轉移的腳本配置

在此版本中，您現在可以在測試故障轉移過程中啟動虛擬機器後在其上執行腳本。這使您能夠測試和驗證腳本。例如，您可以更新 NFS 掛載以指向新的目標伺服器，確保來賓應用程式完全在線，並且可以端對端測試您的復原過程。

有關故障轉移過程的更多信息，請參閱link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["將應用程式容錯移轉至遠端站台"]。



=== 改進的故障恢復過程

在故障轉移期間，故障回復過程現在已停用，直到發現完成。這可確保在啟動故障復原之前正確識別和考慮所有配置，並降低發生錯誤的風險。

有關故障恢復過程的更多信息，請參閱link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failback.html["將應用程式故障回復到原始來源"]。



== 2025年8月4日

版本 4.2.5P2



=== BlueXP disaster recovery更新

此版本包含下列更新：

* 改進了 VMFS 支持，以處理來自多個儲存虛擬機的相同 LUN。
* 改進了測試拆卸清理以處理已卸載或刪除的資料儲存。
* 改進了子網路映射，以便現在可以驗證輸入的網關是否包含在提供的網路中。
* 解決了虛擬機器名稱包含“.com”時可能導致複製計劃失敗的問題。
* 在建立複製計劃的過程中，刪除了封鎖目標磁碟區與來源磁碟區相同的限制。
* 在 Azure 市場中新增了對NetApp智慧服務的即用即付 (PAYGO) 訂閱支持，並在免費試用對話方塊中新增了 Azure 市場的連結。
+
有關詳細信息，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html#licensing["BlueXP disaster recovery許可"]和 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["設定 BlueXP 災難恢復的授權"]。





== 2025 年 14 月 7 日

版本 4.2.5



=== BlueXP disaster recovery中的使用者角色

BlueXP disaster recovery現在採用角色來管理每個使用者對特定功能和操作的存取權。

該服務使用特定於BlueXP disaster recovery的以下角色。

* *災難復原管理員*：在BlueXP disaster recovery中執行任何操作。
* *災難復原故障轉移管理員*：在BlueXP disaster recovery中執行故障轉移和遷移操作。
* *災難復原應用程式管理員*：建立和修改複製計畫並啟動測試故障轉移。
* *災難復原檢視器*：查看BlueXP disaster recovery中的信息，但不能執行任何操作。


如果您按一下BlueXP disaster recovery服務並首次進行配置，則必須具有 *SnapCenterAdmin* 權限或具有 *Organization Admin* 角色。

如需詳細資訊、請參閱  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["BlueXP disaster recovery中的使用者角色和權限"]。

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["了解所有服務的 BlueXP 存取角色"^]。



=== BlueXP disaster recovery中的其他更新

* 增強網路發現
* 可擴展性改進：
+
** 過濾所需的元資料而不是所有細節
** 發現改進，可以更快地檢索和更新虛擬機器資源
** 資料檢索和資料更新的記憶體優化和效能優化
** vCenter SDK 用戶端建立和池管理改進


* 下次計劃或手動發現時的陳舊資料管理：
+
** 當在 vCenter 中刪除虛擬機器時， BlueXP disaster recovery現在會自動將其從複製計劃中刪除。
** 當 vCenter 中刪除資料儲存區或網路時， BlueXP disaster recovery現在會將其從複製計劃和資源群組中刪除。
** 當在 vCenter 中刪除叢集、主機或資料中心時， BlueXP disaster recovery現在會將其從複製計劃和資源群組中刪除。


* 現在，您可以在瀏覽器的隱身模式下存取 Swagger 文件。您可以在BlueXP disaster recovery中透過「設定」選項 > 「API 文件」存取它，也可以在瀏覽器的隱身模式下直接透過以下 URL 存取它：  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Swagger 文件"^] 。
* 在某些情況下，故障回復操作完成後，iGroup 會被遺留。如果 iGroup 已過期，此更新會將其移除。
* 如果複製計畫中使用了 NFS FQDN， BlueXP disaster recovery現在會將其解析為 IP 位址。如果災難復原網站無法解析 FQDN，則此更新非常有用。
* UI 對齊改進
* 成功發現後，記錄擷取 vCenter 大小詳細資訊的日誌改進




== 2025 年 6 月 30 日

4.2.4P2 版



=== 發現改進

此更新改進了發現過程，從而減少了發現所需的時間。



== 2025 年 6 月 23 日

4.2.4P1 版



=== 子網映射改進

本次更新增強了「新增和編輯子網路映射」對話框，新增了搜尋功能。現在，您可以透過輸入搜尋字詞快速尋找特定子網，從而更輕鬆地管理子網映射。



== 2025 年 6 月 9 日

版本 4.2.4



=== Windows 本機管理員密碼解決方案 (LAPS) 支持

Windows 本機管理員密碼解決方案 (Windows LAPS) 是一項 Windows 功能，可自動管理和備份 Active Directory 上本機管理員帳戶的密碼。

現在，您可以透過提供網域控制器詳細資訊來選擇子網路對映選項並檢查 LAPS 選項。使用此選項，您無需為每個虛擬機器提供密碼。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



== 2025 年 13 月 5 日

版本 4.2.3



=== 子網路對應

在此版本中，您可以使用子網路對應，以新的方式管理容錯移轉時的 IP 位址，讓您為每個 vCenter 新增子網路。這樣做時，您可以定義每個虛擬網路的 IPv4 CIDR ，預設閘道和 DNS 。

在容錯移轉時， BlueXP  災難恢復會查看為對應虛擬網路提供的 CIDR ，並使用它來衍生新的 IP 位址，藉此判斷每個 vNIC 的適當 IP 位址。

例如：

* 網路 A = 10.1.1.0/24
* 網路 B = 192.168.1.0/24


VM1 具有連接至網路 A 的 VNIC （ 10.1.1.50 ）。網路 A 會對應到複寫計畫設定中的網路 B 。

在容錯移轉時， BlueXP  災難恢復會取代原始 IP 位址（ 10.1.1 ）的網路部分，並保留原始 IP 位址（ 10.1.1.50 ）的主機位址（ .50 ）。對於 VM1 ， BlueXP  災難恢復會查看網路 B 的 CIDR 設定，並使用網路 B 網路部份 192.168.1 ，同時保留主機部份（ .50 ）來為 VM1 建立新的 IP 位址。新 IP 會變成 192.168.1.50 。

總而言之，主機位址保持不變，而網路位址則會取代站台子網路對應中所設定的任何項目。這可讓您更輕鬆地在容錯移轉時管理 IP 位址重新指派，尤其是當您有數百個網路和數千個 VM 需要管理時。

有關在站點中包括子網映射的詳細信息，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["新增 vCenter 伺服器站台"]。



=== 跳過保護

您現在可以略過保護，這樣在複寫計畫容錯移轉之後，服務就不會自動建立反向保護關係。如果您想要在還原的網站上執行其他作業，然後在 BlueXP  災難恢復中將其重新上線，這項功能就很實用。

當您啟動容錯移轉時，如果原始來源站台在線上，依預設，服務會自動為複寫計畫中的每個磁碟區建立反向保護關係。這表示該服務會從目標站台建立 SnapMirror 關係，並將其還原至來源站台。當您啟動容錯回復時，服務也會自動反轉 SnapMirror 關係。

啟動容錯移轉時，您現在可以選擇 * 略過保護 * 選項。如此一來，服務就不會自動反轉 SnapMirror 關係。而是將可寫入的磁碟區保留在複寫計畫的兩側。

原始來源網站恢復上線後，您可以從「複寫計畫動作」功能表中選取「 * 保護資源 * 」，以建立反向保護。這會嘗試為計畫中的每個磁碟區建立反向複寫關係。您可以重複執行此工作，直到還原保護為止。還原保護時，您可以依照一般方式啟動容錯回復。

有關跳過保護的詳細信息，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["將應用程式容錯移轉至遠端站台"]。



=== SnapMirror 會在複寫計畫中排程更新

BlueXP  災難恢復現在支援使用外部快照管理解決方案，例如原生 ONTAP SnapMirror 原則排程器或與 ONTAP 的協力廠商整合。如果複寫計畫中的每個資料存放區（ Volume ）都已有 SnapMirror 關係，而該關係正在其他地方管理，您可以將這些快照作為 BlueXP  災難恢復的恢復點。

若要設定，請在「複寫計畫」 > 「資源對應」區段中，勾選「設定資料存放區對應時，使用平台管理的備份和保留排程 * 」核取方塊。

選取此選項時， BlueXP  災難恢復不會設定備份排程。不過，您仍需要設定保留排程，因為仍可能需要拍攝快照來執行測試，容錯移轉和容錯回復作業。

設定此選項之後，服務不會定期擷取任何排程的快照，而是仰賴外部實體來拍攝和更新這些快照。

如需在複寫計畫中使用外部快照解決方案的詳細資訊，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



== 2025 年 4 月 16 日

版本 4.2.2



=== 虛擬機器排程探索

BlueXP  災難恢復每 24 小時執行一次發現。有了這個版本，您現在可以自訂探索排程，以滿足您的需求，並在需要時降低對效能的影響。例如，如果您有大量 VM ，則可以將探索排程設定為每 48 小時執行一次。如果 VM 數量不多，您可以將探索排程設定為每 12 小時執行一次。

如果您不想排程探索，您可以停用排程探索選項，並隨時手動重新整理探索。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["新增 vCenter 伺服器站台"]參閱。



=== 資源群組資料存放區支援

以前，您只能由 VM 建立資源群組。在此版本中，您可以依資料存放區建立資源群組。當您建立複寫計畫並為該計畫建立資源群組時，資料存放區中的所有 VM 都會列出。如果您有大量虛擬機器，而且想要依資料存放區將其分組，這項功能就很實用。

您可以使用下列方式建立具有資料存放區的資源群組：

* 當您使用資料存放區新增資源群組時，可以看到資料存放區清單。您可以選取一或多個資料存放區來建立資源群組。
* 當您建立複寫計畫並在計畫中建立資源群組時，可以在資料存放區中看到 VM 。


如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== 免費試用或授權到期通知

此版本會通知您免費試用將在 60 天內到期，以確保您有時間取得授權。此版本也會在授權到期日提供通知。



=== 服務更新通知

在此版本中，頂端會出現橫幅，表示服務正在升級，且服務處於維護模式。升級服務時會顯示橫幅，升級完成後會消失。雖然您可以在升級進行期間繼續在 UI 中工作，但您無法提交新工作。排程工作會在更新完成後執行，服務會返回正式作業模式。



== 2025 年 3 月 10 日

版本 4.2.1



=== 智慧型 Proxy 支援

BlueXP  Connector 支援智慧型 Proxy 。智慧型 Proxy 是一種輕量，安全且有效率的方法，可將內部環境連線至 BlueXP  服務。它可在您的環境和 BlueXP  服務之間提供安全連線，而不需要 VPN 或直接網際網路存取。這項最佳化的 Proxy 實作可卸載本機網路內的 API 流量。

設定 Proxy 時， BlueXP  災難恢復會嘗試直接與 VMware 或 ONTAP 通訊，並在直接通訊失敗時使用設定的 Proxy 。

BlueXP  災難恢復 Proxy 實作需要連接器與任何 vCenter Server 和 ONTAP 陣列之間使用 HTTPS 通訊協定進行連接埠 443 通訊。Connector 內的 BlueXP  災難恢復代理程式在執行任何動作時，會直接與 VMware vSphere ， VC 或 ONTAP 通訊。

如需 BlueXP  災難恢復智慧型 Proxy 的詳細資訊，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["為 BlueXP 災難恢復設定基礎架構"]。

如需在 BlueXP  中設定一般 Proxy 的詳細資訊，請參閱 https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["設定連接器以使用Proxy伺服器"^]。



=== 隨時結束免費試用

您可以在任何時間停止免費試用，也可以等到試用期到期。

請參閱。 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["結束免費試用"]



== 2025 年 19 月 2 日

版本 4.2



=== ASA R2 支援 VMFS 儲存設備上的 VM 和資料存放區

此版本的 BlueXP  災難恢復可為 VMFS 儲存設備上的虛擬機器和資料存放區提供 ASA R2 支援。在 ASA R2 系統上， ONTAP 軟體支援基本的 SAN 功能，同時移除 SAN 環境中不支援的功能。

此版本支援 ASA R2 的下列功能：

* 主要儲存設備的一致性群組資源配置（僅限平面一致性群組，表示只有一個層級沒有階層式結構）
* 備份（一致性群組）作業，包括 SnapMirror 自動化


BlueXP  災難恢復中對 ASA R2 的支援使用 ONTAP 9.16.1 。

雖然資料存放區可以掛載在 ONTAP 磁碟區或 ASA R2 儲存單元上，但 BlueXP  災難恢復中的資源群組不能同時包含來自 ONTAP 的資料存放區和來自 ASA R2 的資料存放區。您可以從 ONTAP 選取資料存放區，或從資源群組中的 ASA R2 選取資料存放區。



== 2024 年 10 月 30 日



=== 報告

您現在可以產生及下載報告、以協助您分析環境。預先設計的報告會摘要容錯移轉和容錯移轉、顯示所有站台的複寫詳細資料、以及顯示過去七天的工作詳細資料。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["建立災難恢復報告"]。



=== 30 天免費試用

您現在可以註冊免費試用 30 天的 BlueXP  災難恢復。以前、免費試用期為 90 天。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["設定授權"]。



=== 停用及啟用複寫計畫

先前版本包含容錯移轉測試排程結構的更新、這是支援每日和每週排程所需的更新。此更新需要您停用並重新啟用所有現有的複寫計畫、才能使用新的每日和每週容錯移轉測試排程。這是一次性要求。

方法如下：

. 從上方功能表中、選取 * 複寫計畫 * 。
. 選取計畫、然後選取「動作」圖示以顯示下拉式功能表。
. 選擇*停用*。
. 幾分鐘後、選取 * 啟用 * 。




=== 資料夾對應

建立複寫計畫和對應運算資源時、您現在可以對應資料夾、以便將 VM 恢復到您指定的資料夾中、以供資料中心、叢集和主機使用。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== VM 詳細資料可用於容錯移轉、容錯回復及測試容錯移轉

當發生故障、而您正在啟動容錯移轉、執行容錯回復或測試容錯移轉時、您現在可以查看 VM 的詳細資料、並識別哪些 VM 未重新啟動。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["將應用程式容錯移轉至遠端站台"]。



=== VM 開機延遲、並依序執行開機順序

建立複寫計畫時、您現在可以為計畫中的每個 VM 設定開機延遲。這可讓您設定 VM 開始的順序、以確保在啟動後續優先順序 VM 之前、有一個 VM 正在執行所有優先順序。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== VM 作業系統資訊

當您建立複寫計畫時、現在可以在計畫中看到每個 VM 的作業系統。這有助於決定如何將 VM 群組在資源群組中。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== VM 名稱別名

當您建立複寫計畫時、現在可以在災難恢復會議上新增 VM 名稱的前置字元和後置字元。這可讓您在計畫中為 VM 使用更具描述性的名稱。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== 清理舊的快照

您可以刪除任何超出指定保留數量的不再需要的快照。快照可能會隨著時間而累積、因此您可以減少快照保留數量、然後移除快照以釋出空間。您可以隨時視需要或刪除複寫計畫來執行此作業。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理站台、資源群組、複寫計畫、資料存放區和虛擬機器資訊"]參閱。



=== 協調快照

您現在可以協調來源和目標之間不同步的快照。如果在 BlueXP  災難恢復之外的目標上刪除快照、可能會發生這種情況。服務會每 24 小時自動刪除來源上的快照。不過、您可以隨需執行此作業。此功能可讓您確保所有站台的快照一致。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理複寫計畫"]參閱。



== 2024 年 9 月 20 日



=== 支援內部部署到內部部署的 VMware VMFS 資料存放區

此版本支援安裝在 VMware vSphere 虛擬機器檔案系統（ VMFS ）資料存放區上的虛擬機器、以供 iSCSI 和 FC 受內部部署儲存保護。此服務先前提供 _ 技術預覽 _ 、支援 iSCSI 和 FC 的 VMFS 資料存放區。

以下是 iSCSI 和 FC 通訊協定的其他考量事項：

* FC 支援適用於用戶端前端通訊協定、而非複寫。
* BlueXP  災難恢復每個 ONTAP 磁碟區僅支援單一 LUN 。磁碟區不應有多個 LUN 。
* 對於任何複寫計畫、目的地 ONTAP Volume 應使用與主控受保護 VM 的來源 ONTAP Volume 相同的傳輸協定。例如、如果來源使用 FC 傳輸協定、則目的地也應該使用 FC 。




== 2024 年 8 月 2 日



=== 支援內部部署到內部部署的 VMware VMFS FC 資料存放區

此版本包含 _ 技術預覽 _ 、可支援安裝在 VMware vSphere 虛擬機器檔案系統（ VMFS ）資料存放區上的 VM 、以供 FC 保護至內部部署儲存設備。此服務先前提供技術預覽、可支援 iSCSI 的 VMFS 資料存放區。


NOTE: NetApp 不收取任何預覽工作負載容量的費用。



=== 工作取消

使用此版本、您現在可以在工作監控 UI 中取消工作。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["監控工作"]。



== 2024 年 7 月 17 日



=== 容錯移轉測試排程

此版本包含容錯移轉測試排程結構的更新、這是支援每日和每週排程所需的更新。此更新需要您停用並重新啟用所有現有的複寫計畫、才能使用新的每日和每週容錯移轉測試排程。這是一次性要求。

方法如下：

. 從上方功能表中、選取 * 複寫計畫 * 。
. 選取計畫、然後選取「動作」圖示以顯示下拉式功能表。
. 選擇*停用*。
. 幾分鐘後、選取 * 啟用 * 。




=== 複寫計畫更新

此版本包含複寫計畫資料的更新、可解決「找不到快照」的問題。這需要您將所有複寫計畫中的保留計數變更為 1 、然後啟動隨需快照。此程序會建立新的備份、並移除所有較舊的備份。

方法如下：

. 從上方功能表中、選取 * 複寫計畫 * 。
. 選取複寫計畫、按一下 * 容錯移轉對應 * 標籤、然後按一下 * 編輯 * 鉛筆圖示。
. 按一下 * 資料存放區 * 箭號加以展開。
. 請注意複寫計畫中保留計數的值。完成這些步驟後、您必須恢復此原始值。
. 將數量減至 1 。
. 啟動隨選快照。若要這麼做、請在「複寫計畫」頁面上選取計畫、按一下「動作」圖示、然後選取 * 立即擷取快照 * 。
. 快照工作成功完成後、請將複寫計畫中的計數增加回您在第一步中記下的原始值。
. 對所有現有的複寫計畫重複這些步驟。




== 2024 年 7 月 5 日

此 BlueXP 災難恢復版本包含下列更新：



=== 支援 AFF A 系列

此版本支援 NetApp AFF A 系列硬體平台。



=== 支援內部部署到內部部署的 VMware VMFS 資料存放區

此版本包含 _ 技術預覽 _ 、可支援安裝在 VMware vSphere 虛擬機器檔案系統（ VMFS ）資料存放區上、並受保護至內部部署儲存設備的 VM 。此版本支援災難恢復功能、可在內部部署 VMware 工作負載的技術預覽中進行、並可在內部部署 VMware 環境中使用 VMFS 資料存放區。


NOTE: NetApp 不收取任何預覽工作負載容量的費用。



=== 複寫計畫更新

您可以在「應用程式」頁面上依資料存放區篩選虛擬機器、並在「資源對應」頁面上選取更多目標詳細資料、以更輕鬆地新增複寫計畫。請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== 編輯複寫計畫

此版本已增強容錯移轉對應頁面、以獲得更清楚的資訊。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理計畫"]。



=== 編輯 VM

在此版本中、規劃中的虛擬機器編輯程序包括一些細微的 UI 改善。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理 VM"]。



=== 容錯移轉更新

在您啟動容錯移轉之前、您現在可以判斷 VM 的狀態、以及 VM 的電源是開啟還是關閉。現在、容錯移轉程序可讓您立即拍攝快照、或選擇快照。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["將應用程式容錯移轉至遠端站台"]。



=== 容錯移轉測試排程

您現在可以編輯容錯移轉測試、並設定容錯移轉測試的每日、每週和每月排程。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理計畫"]。



=== 更新必要資訊

BlueXP  災難恢復先決條件資訊已更新。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["BlueXP 災難恢復先決條件"]。



== 2024 年 5 月 15 日

此 BlueXP 災難恢復版本包含下列更新：



=== 將 VMware 工作負載從內部部署複寫到內部部署

這項功能現在已作為一般可用度功能發行。以前、這是一項功能有限的技術預覽。



=== 授權更新

有了 BlueXP  災難恢復功能、您可以註冊 90 天免費試用版、透過 Amazon Marketplace 購買隨付（ PAYGO ）訂閱、或自帶授權（ BYOL ）、這是您從 NetApp 銷售代表或 NetApp 支援網站（ NSS ）取得的 NetApp 授權檔案（ NLF ）。

如需設定 BlueXP 災難恢復授權的詳細資訊、請參閱 link:../get-started/dr-licensing.html["設定授權"]。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["深入瞭解 BlueXP 災難恢復"]。



== 2024 年 3 月 5 日

這是 BlueXP 災難恢復的一般可用度版本、其中包括下列更新。



=== 授權更新

透過 BlueXP  災難恢復、您可以註冊 90 天免費試用版、或自帶授權（ BYOL ）、這是您從 NetApp 銷售代表處取得的 NetApp 授權檔案（ NLF ）您可以使用授權序號、在 BlueXP 數位錢包中啟動 BYOL 。BlueXP 災難恢復費用是根據資料存放區的已配置容量而定。

如需設定 BlueXP 災難恢復授權的詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["設定授權"]。

如需管理 * 全部 * BlueXP 服務授權的詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["管理所有 BlueXP 服務的授權"^]。



=== 編輯排程

有了這個版本、您現在可以設定測試法規遵循和容錯移轉測試的排程、確保它們在您需要時能正常運作。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



== 2024 年 2 月 1 日

此 BlueXP 災難恢復預覽版本包含下列更新：



=== 網路強化

使用此版本、您現在可以調整 VM CPU 和 RAM 值的大小。您現在也可以為虛擬機器選取網路 DHCP 或靜態 IP 位址。

* DHCP ：如果您選擇此選項、則會提供 VM 的認證。
* 靜態 IP ：您可以從來源 VM 選取相同或不同的資訊。如果您選擇的來源相同、則不需要輸入認證。另一方面、如果您選擇使用來源的不同資訊、則可以提供認證、 IP 位址、子網路遮罩、 DNS 和閘道資訊。


如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== 自訂指令碼

現在可以納入容錯移轉後程序。透過自訂指令碼、您可以在容錯移轉程序之後執行 BlueXP 災難恢復指令碼。例如、您可以使用自訂指令碼、在容錯移轉完成後恢復所有資料庫交易。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["容錯移轉至遠端站台"]。



=== SnapMirror關係

您現在可以在開發複寫計畫時建立 SnapMirror 關係。以前、您必須在 BlueXP 災難恢復之外建立關係。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== 一致性群組

建立複寫計畫時、您可以納入來自不同磁碟區和不同 SVM 的 VM 。BlueXP 災難恢復通過包括所有卷並更新所有輔助位置來創建一致性組快照。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== VM 開機延遲選項

建立複寫計畫時、您可以將 VM 新增至資源群組。使用資源群組、您可以在每個 VM 上設定延遲、以便它們啟動延遲的順序。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== 應用程式一致的Snapshot複本

您可以指定建立應用程式一致的 Snapshot 複本。服務將會先將應用程式設為「自動快照」、然後再製作「快照」、以取得應用程式的一致狀態。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



== 2024 年 1 月 11 日

此 BlueXP 災難恢復預覽版本包含下列更新：



=== 儀表板更快速

使用此版本、您可以更快速地從儀表板存取其他頁面上的資訊。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["瞭解 BlueXP 災難恢復"]。



== 2023 年 10 月 20 日

此 BlueXP 災難恢復預覽版本包含下列更新。



=== 保護內部部署的 NFS 型 VMware 工作負載

現在有了 BlueXP 災難恢復功能、除了公有雲之外、您還可以保護內部部署的 NFS 型 VMware 工作負載、使其免受災難影響、不受其他內部部署、 NFS 型 VMware 環境的影響。BlueXP 災難恢復可協調災難恢復計畫的完成。


NOTE: 透過此預覽方案、 NetApp 保留在「一般供應」之前修改產品詳細資料、內容和時間表的權利。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["深入瞭解 BlueXP 災難恢復"]。



== 2023 年 9 月 27 日

此 BlueXP 災難恢復預覽版本包含下列更新：



=== 儀表板更新

您現在可以按一下儀表板上的選項、以便更輕鬆地快速檢閱資訊。此外、儀表板現在也會顯示容錯移轉和移轉的狀態。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["在儀表板上檢視災難恢復計畫的健全狀況"]。



=== 複寫計畫更新

* * RPO * ：您現在可以在複寫計畫的資料存放區區區區段中輸入恢復點目標（ RPO ）和保留計數。這表示必須存在的資料量、其長度不得早於設定時間。例如、如果您將其設為 5 分鐘、則在發生災難而不影響業務關鍵需求的情況下、系統最多可能會遺失 5 分鐘的資料。
+
請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。

* * 網路功能增強 * ：當您在複寫計畫的虛擬機器區段中對應來源和目標位置之間的網路時、 BlueXP 災難恢復現在提供兩個選項： DHCP 或靜態 IP 。以前只支援 DHCP 。對於靜態 IP 、您可以設定子網路、閘道和 DNS 伺服器。此外、您現在可以輸入虛擬機器的認證。
+
請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。

* * 編輯排程 * ：您現在可以更新複寫計畫排程。
+
請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理資源"]。

* *SnapMirror 自動化 * ：當您在此版本中建立複寫計畫時、您可以在下列其中一個組態中定義來源磁碟區與目標磁碟區之間的 SnapMirror 關係：
+
** 1 對 1
** 在扇出架構中有 1 對多個
** 一致性群組中有多對 1
** 多到多
+
請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。







== 2023 年 8 月 1 日



=== BlueXP  災難恢復預覽

BlueXP 災難恢復預覽是一種雲端型災難恢復服務、可自動化災難恢復工作流程。最初、透過 BlueXP 災難恢復預覽、您可以保護內部部署、以 NFS 為基礎的 VMware 工作負載、在 AWS 上執行 NetApp 儲存設備、將其移轉至 VMware Cloud （ VMC ）、並搭配 Amazon FSX for ONTAP 。


NOTE: 透過此預覽方案、 NetApp 保留在「一般供應」之前修改產品詳細資料、內容和時間表的權利。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["深入瞭解 BlueXP 災難恢復"]。

此版本包含下列更新：



=== 開機順序的資源群組更新

建立災難恢復或複寫計畫時、您可以將虛擬機器新增至功能性資源群組。資源群組可讓您將一組相關的虛擬機器放入符合您需求的邏輯群組。例如、群組可能包含可在恢復時執行的開機順序。在此版本中、每個資源群組可以包含一或多個虛擬機器。虛擬機器將根據您將其納入計畫的順序來啟動。請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["選取要複寫及指派資源群組的應用程式"]。



=== 複寫驗證

建立災難恢復或複寫計畫後、請在精靈中識別週期、並開始複寫至災難恢復站台、每 30 分鐘 BlueXP  災難恢復就會驗證複寫是否確實根據計畫進行。您可以在「工作監控」頁面中監控進度。請參閱  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["將應用程式複寫到另一個站台"]。



=== 複寫計畫顯示恢復點目標（ RPO ）傳輸排程

當您建立災難恢復或複寫計畫時、請選取虛擬機器。在此版本中、您現在可以檢視與資料存放區或 VM 相關聯的每個磁碟區相關聯的 SnapMirror 。您也可以查看與 SnapMirror 排程相關的 RPO 傳輸排程。RPO 可協助您判斷備份排程是否足以在災難後恢復。請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== 工作監控更新

「工作監控」頁面現在包含「重新整理」選項、可讓您取得最新的作業狀態。請參閱  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["監控災難恢復工作"]。



== 2023 年 5 月 18 日

這是 BlueXP 災難恢復的初始版本。



=== 雲端型災難恢復服務

BlueXP 災難恢復是一種雲端型災難恢復服務、可自動化災難恢復工作流程。最初、透過 BlueXP 災難恢復預覽、您可以保護內部部署、以 NFS 為基礎的 VMware 工作負載、在 AWS 上執行 NetApp 儲存設備、將其移轉至 VMware Cloud （ VMC ）、並搭配 Amazon FSX for ONTAP 。

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["深入瞭解 BlueXP 災難恢復"]。
